import type { Risk } from "./risk";

const now = Date.now();
const daysAgo = (n: number) => new Date(now - n * 86400000).toISOString();

export const seedRisks: Risk[] = [
  {
    id: "seed-aml-01",
    projectId: "AML_01",
    riskId: "1001",
    email: "md.rofiquzzaman@akijresource.com",
    dateRaised: "2026-01-14",
    projectName: "Akij Mediplex",
    projectZone: "Mirpur-10",
    identifierName: "Md Rofiquzzaman",
    identifierEmpId: "570903",
    category: "Technical",
    description: "Cables stolen at site.",
    likelihood: "Low",
    impact: "High",
    riskResponsible: "Security guard",
    riskAccountable: "Alex Ruben",
    mitigation: "Enhance security patroling",
    status: "Closed",
    attachmentName: "",
    attachmentUrl: "",
    createdAt: daysAgo(12),
    updatedAt: daysAgo(3),
    updates: [
      {
        id: "u-aml-01-1",
        at: daysAgo(3),
        by: "Alex Ruben",
        status: "Closed",
        note: "Security patrol enhanced and incident closed after review.",
      },
    ],
  },
  {
    id: "seed-alel-01",
    projectId: "ALEL_01",
    riskId: "1002",
    email: "md.shakil@akijresource.com",
    dateRaised: "2026-02-16",
    projectName: "Akij Light Engineering",
    projectZone: "Narayanganj",
    identifierName: "Md Shakil",
    identifierEmpId: "568632",
    category: "Technical",
    description: "Temperature control of air conditioner not performing to requirement.",
    likelihood: "Low",
    impact: "High",
    riskResponsible: "User",
    riskAccountable: "Md Shakil",
    mitigation: "Maintenance cooling system",
    status: "Closed",
    attachmentName: "",
    attachmentUrl: "",
    createdAt: daysAgo(10),
    updatedAt: daysAgo(2),
    updates: [
      {
        id: "u-alel-01-1",
        at: daysAgo(2),
        by: "Md Shakil",
        status: "Closed",
        note: "Cooling system maintenance completed.",
      },
    ],
  },
  {
    id: "seed-alel-02",
    projectId: "ALEL_02",
    riskId: "1003",
    email: "mirsohel.rana@akijresource.com",
    dateRaised: "2026-01-05",
    projectName: "Akij Light Engineering",
    projectZone: "Narayanganj",
    identifierName: "Mir Sohel Rana",
    identifierEmpId: "559464",
    category: "Safety",
    description: "Safety incident reported at site during execution.",
    likelihood: "Low",
    impact: "High",
    riskResponsible: "MD. Abdur Razzak Babu",
    riskAccountable: "Mir Sohel Rana",
    mitigation:
      "Conduct toolbox talks and safety inspections before each shift.",
    status: "Open",
    attachmentName: "",
    attachmentUrl: "",
    createdAt: daysAgo(8),
    updatedAt: daysAgo(1),
    updates: [
      {
        id: "u-alel-02-1",
        at: daysAgo(1),
        by: "Mir Sohel Rana",
        status: "Open",
        note: "Toolbox talks scheduled; waiting for inspection sign-off.",
      },
    ],
  },
  {
    id: "seed-alel-03",
    projectId: "ALEL_03",
    riskId: "1004",
    email: "mirsohel.rana@akijresource.com",
    dateRaised: "2026-01-06",
    projectName: "Akij Light Engineering",
    projectZone: "Narayanganj",
    identifierName: "Mir Sohel Rana",
    identifierEmpId: "559464",
    category: "Quality",
    description: "Material quality not meeting specification.",
    likelihood: "Medium",
    impact: "High",
    riskResponsible: "Asif Bhuiyan",
    riskAccountable: "Mir Sohel Rana",
    mitigation:
      "Conduct pre-delivery inspections, approve samples before procurement and perform QC checks upon delivery.",
    status: "Open",
    attachmentName: "",
    attachmentUrl: "",
    createdAt: daysAgo(6),
    updatedAt: daysAgo(1),
    updates: [],
  },
  {
    id: "seed-alel-04",
    projectId: "ALEL_04",
    riskId: "1005",
    email: "mirsohel.rana@akijresource.com",
    dateRaised: "2025-02-20",
    projectName: "Akij Light Engineering",
    projectZone: "Narayanganj",
    identifierName: "Mir Sohel Rana",
    identifierEmpId: "559464",
    category: "Resource",
    description: "Shortage of skilled manpower affecting execution progress.",
    likelihood: "Medium",
    impact: "High",
    riskResponsible: "Asif Bhuiyan",
    riskAccountable: "Mir Sohel Rana",
    mitigation: "Arrange additional manpower from alternate sources.",
    status: "Open",
    attachmentName: "",
    attachmentUrl: "",
    createdAt: daysAgo(5),
    updatedAt: daysAgo(1),
    updates: [],
  },
  {
    id: "seed-alel-05",
    projectId: "ALEL_05",
    riskId: "1006",
    email: "mirsohel.rana@akijresource.com",
    dateRaised: "2025-02-21",
    projectName: "Akij Light Engineering",
    projectZone: "Narayanganj",
    identifierName: "Mir Sohel Rana",
    identifierEmpId: "559464",
    category: "Quality",
    description: "Inadequate supervision on site leading to rework risk.",
    likelihood: "Medium",
    impact: "High",
    riskResponsible: "Paresh Paul",
    riskAccountable: "Mir Sohel Rana",
    mitigation:
      "Assign qualified supervisors and conduct regular site inspections.",
    status: "Open",
    attachmentName: "",
    attachmentUrl: "",
    createdAt: daysAgo(4),
    updatedAt: daysAgo(1),
    updates: [],
  },
];
